// Code generated by logcopter-gen; DO NOT EDIT.

package launcher

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-wm.pkg.launcher")
